### ISSUE TITLE
Illegal reflective access operation

### ISSUE THREAD

**Issue by 70853n** [webcompere/system-stubs#34] opened 2021-08-20 15:44 UTC
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by uk.org.webcompere.systemstubs.environment.EnvironmentVariables (file:/Users/user/.m2/repository/uk/org/webcompere/system-stubs-core/1.2.0/system-stubs-core-1.2.0.jar) to field java.util.Collections$UnmodifiableMap.m
WARNING: Please consider reporting this to the maintainers of uk.org.webcompere.systemstubs.environment.EnvironmentVariables
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
**WARNING: All illegal access operations will be denied in a future release**

**Comment by ashleyfrieze** [comment] 2021-08-20 15:46
Duplicate of #32

**Closed as completed by ashleyfrieze** 2021-08-20 15:46 UTC

**Comment by ashleyfrieze** [comment] 2021-08-20 15:49
@70853n I've left a long explanation in #32
